name: Repo Audit (GA, SEO, Economics)
on: [push, workflow_dispatch]

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check required files
        run: |
          req=("index.html" "analytics.js" "robots.txt" "sitemap.xml" "LICENSE_SCIENCE.md" "LICENSE_COMMERCIAL.md" "economics/ledger.json" "economics/prices.yaml" ".zenodo.json")
          miss=0
          for f in "${req[@]}"; do
            if [ ! -f "$f" ]; then echo "MISSING: $f"; miss=1; fi
          done
          [ $miss -eq 0 ]

      - name: Validate GA4 presence
        run: |
          id=$(grep -Eo "gtag\\('config',\\s*'G-[A-Z0-9]+'\\)" index.html | head -n1 | sed "s/.*'\\(G-[A-Z0-9]\\+\\)'.*/\\1/")
          echo "GA_ID=$id"
          test -n "$id"

      - name: Validate JSON files
        run: |
          python - << 'PY'
import json
for fn in [".zenodo.json","economics/ledger.json"]:
    with open(fn,"r",encoding="utf-8") as f:
        json.load(f)
print("JSON OK")
PY

      - name: Basic sitemap check
        run: |
          grep -q "<loc>https://geozunac3536-jpg.github.io/TCDS-Business-Plan/" sitemap.xml

      - name: Economic schema check
        run: |
          python - << 'PY'
import json, sys
d=json.load(open("economics/ledger.json","r",encoding="utf-8"))
if not isinstance(d,list): sys.exit("ledger.json debe ser arreglo")
need={"timestamp","tx_id","type","amount_usd"}
if d:
    miss=need - set(d[0].keys())
    if miss: sys.exit(f"Faltan campos en ledger: {miss}")
print("ECONOMICS OK")
PY
